#!/bin/bash
# Configure and launch a Claude Code sandbox for the current directory.
#
#   ./sbx-up.sh                   # named after $PWD, then attach
#   ./sbx-up.sh --no-run          # create without attaching
#   ./sbx-up.sh -- . ../docs:ro   # extra args for `sbx create`
#
# Covers the host-side steps a kit can't do: sbx settings, secrets, the skills
# store, and staging the host gitconfig (kits can't read host files at create).

set -euo pipefail

# Default sandbox name generated by sbx.
SANDBOX_NAME="claude-`basename $PWD`"
RUN=1
CREATE_ARGS=()

while [ $# -gt 0 ]; do
    case "$1" in
        --no-run)  RUN=0; shift ;;
        --)        shift; CREATE_ARGS=("$@"); break ;;
        -h|--help) sed -n '2,10p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
        *) echo "unknown argument: $1 (use -- to pass args to sbx create)" >&2; exit 1 ;;
    esac
done

[ ${#CREATE_ARGS[@]} -gt 0 ] || CREATE_ARGS=(.)

step() { printf '\n\033[1m==> %s\033[0m\n' "$*"; }
ok()   { printf '\033[32m[✓]\033[0m %s\n' "$*"; }
skip() { printf '\033[90m[skip]\033[0m %s\n' "$*"; }
info() { printf '\033[32m[info]\033[0m %s\n' "$*"; }
warn() { printf '\033[33m[warn]\033[0m %s\n' "$*"; }
error() { printf '\033[31m[err]\033[0m %s\n' "$*"; }

sandbox_exists() {
    sbx ls 2>/dev/null | awk -v n="$SANDBOX_NAME" '$1 == n {found=1} END {exit !found}'
}

set_host_config() {
    step "Host settings"
    sbx settings set clipboard.imagePaste true >/dev/null && ok "clipboard.imagePaste enabled"
    sbx settings set kit.allowLocalKits true >/dev/null && ok "kit.allowLocalKits enabled"
}

set_github_token() {
    step "GitHub credential"
    echo "$(gh auth token)" | sbx secret set -g github
    ok "GitHub token set"
}

create_sandbox() {
    # --kit only applies at create; `sbx kit add` restarts but preserves VM state.
    # sbx kit add "$SANDBOX_NAME" "$KIT_DIR"
    step "Create sandbox '$SANDBOX_NAME'"
    echo "sbx create --name $SANDBOX_NAME ${CREATE_ARGS[@]} claude ."
    sbx create --name "$SANDBOX_NAME" ${CREATE_ARGS[@]} claude .
}

set_git_identity() {
    step "Git identity"
    sbx exec "$SANDBOX_NAME" bash -c "cat >> /etc/sandbox-persistent.sh <<'EOF'
export GIT_USER_NAME=$(git config --global user.name)
export GIT_USER_EMAIL=$(git config --global user.email)
EOF"
    echo "checking...."
    echo `sbx exec "$SANDBOX_NAME" bash -c "cat /etc/sandbox-persistent.sh"`
}

run_sandbox() {
    if sandbox_exists && [ "$RUN" -eq 1 ]; then
        step "Attaching"
        exec sbx run --name "$SANDBOX_NAME"
    else
        echo '\nAttach with: sbx run --name %s\n' "$SANDBOX_NAME"
    fi
}

validate() {
    step "Ready"
    # No --global on the git reads: that scope skips the [include] holding the identity.
    sbx exec "$SANDBOX_NAME" -- bash -lc '
        printf "    git identity : %s <%s>\n" "$GIT_USER_NAME" "$GIT_USER_EMAIL"
        printf "    statusline   : %s\n" "$(jq -r ".statusLine.command // \"NOT SET\"" ~/.claude/settings.json 2>/dev/null)"
        printf "    agent mode   : %s\n" "$(jq -r ".defaultMode // \"default\"" ~/.claude/settings.json 2>/dev/null)"
        printf "    github https : %s\n" "$(gh auth status 2>&1 | grep -qi "logged in\|Active account" && echo "authenticated via proxy" || echo "unauthenticated (public repos only)")"
    ' 2>/dev/null || warn "could not verify sandbox state"
}

main() {
    if sandbox_exists; then
        info "Sandbox '$SANDBOX_NAME' already exists, running it"
    else
        set_host_config
        set_github_token
        create_sandbox
        set_git_identity
    fi
    run_sandbox
}

main
