#!/bin/bash
# Create the sandbox for the current directory if needed, then open a shell in it.
# All arguments are forwarded verbatim to `sbx create`.
#
#   ./sbx-up.sh
#   ./sbx-up.sh --kit ./sbx-postinstall-kit
#   ./sbx-up.sh --kit ./sbx-postinstall-kit ../docs:ro

set -euo pipefail

# Default sandbox name generated by sbx is "claude-<basename>".
BASENAME=${PWD##*/}
SANDBOX_NAME="claude-${BASENAME//[^a-zA-Z0-9.+-]/-}"

step() { printf '\n\033[1m==> %s\033[0m\n' "$*"; }
ok()   { printf '\033[32m[✓]\033[0m %s\n' "$*"; }
skip() { printf '\033[90m[skip]\033[0m %s\n' "$*"; }
info() { printf '\033[32m[info]\033[0m %s\n' "$*"; }
warn() { printf '\033[33m[warn]\033[0m %s\n' "$*"; }
error() { printf '\033[31m[err]\033[0m %s\n' "$*"; }

sandbox_exists() {
    sbx ls 2>/dev/null | awk -v n="$SANDBOX_NAME" '$1 == n {found=1} END {exit !found}'
}

set_host_config() {
    step "Host settings"
    sbx settings set clipboard.imagePaste true >/dev/null && ok "clipboard.imagePaste enabled"
    sbx settings set kit.allowLocalKits true >/dev/null && ok "kit.allowLocalKits enabled"
}

set_github_token() {
    step "GitHub credential"
    echo "$(gh auth token)" | sbx secret set -g github
    ok "GitHub token set"
}

create_sandbox() {
    # --kit only applies at create; `sbx kit add` restarts but preserves VM state.
    # sbx kit add "$SANDBOX_NAME" "$KIT_DIR"
    step "Create sandbox '$SANDBOX_NAME'"
    echo "sbx create --name $SANDBOX_NAME claude . $*"
    sbx create --name "$SANDBOX_NAME" claude . "$@"
}

set_git_identity() {
    step "Git identity"
    GIT_USER_NAME=$(git config --global user.name)
    GIT_USER_EMAIL=$(git config --global user.email)
    GIT_COMMANDS="git config user.name $GIT_USER_NAME; git config user.email $GIT_USER_EMAIL"
    sbx exec "$SANDBOX_NAME" bash -c "echo $GIT_COMMANDS >> /etc/sandbox-persistent.sh"
}

# Make sure the default permission is --dangerously-skip-permissions
# as it overridden in "run_sandbox".
setup_claude_full_permissions() {
    printf '%s\n' 'claude() { command claude --dangerously-skip-permissions "$@"; }' \
        | sbx exec -i "$SANDBOX_NAME" bash -c 'cat >> /etc/sandbox-persistent.sh'
}

run_sandbox() {
    step "Opening shell"
    exec sbx exec -it "$SANDBOX_NAME" bash
}

validate() {
    step "Ready"
    # No --global on the git reads: that scope skips the [include] holding the identity.
    sbx exec "$SANDBOX_NAME" -- bash -lc '
printf "    git identity : %s\n" `git config list | grep name`
printf "    statusline   : %s\n" "$(jq -r ".statusLine.command // \"NOT SET\"" ~/.claude/settings.json 2>/dev/null)"
printf "    agent mode   : %s\n" "$(jq -r ".defaultMode // \"default\"" ~/.claude/settings.json 2>/dev/null)"
printf "    github https : %s\n" "$(gh auth status 2>&1 | grep -qi "logged in\|Active account" && echo "authenticated via proxy" || echo "unauthenticated (public repos only)")"
' 2>/dev/null || warn "could not verify sandbox state"
}

main() {
    if sandbox_exists; then
        info "Sandbox '$SANDBOX_NAME' already exists, running it"
    else
        set_host_config
        set_github_token
        create_sandbox "$@"
        set_git_identity
        setup_claude_full_permissions
    fi
    # validate
    run_sandbox
}

main "$@"
