#!/bin/bash
# Create the sandbox for the current directory if needed, then open a shell in it.
# All arguments are forwarded verbatim to `sbx create`.
#
#   ./sbxc.sh
#   ./sbxc.sh --kit ./statusline-kit
#   ./sbxc.sh --kit ./statusline-kit ../docs:ro

set -euo pipefail

# Default sandbox name generated by sbx is "claude-<basename>".
BASENAME=${PWD##*/}
SANDBOX_NAME="claude-${BASENAME//[^a-zA-Z0-9.+-]/-}"

# $'...' so these hold real escape characters, usable directly in a format string.
RESET=$'\033[0m'
BOLD=$'\033[1m'
RED=$'\033[31m'
GREEN=$'\033[32m'
YELLOW=$'\033[33m'
CYAN=$'\033[36m'
GREY=$'\033[90m'

title() { printf "\n${BOLD}%s${RESET} ${GREY}%s${RESET}\n" "$1" "${2-}"; }
ok()    { printf "  ${GREEN}✔${RESET} %s\n" "$*"; }
run()   { printf "  ${CYAN}→${RESET} %s\n" "$*"; }
warn()  { printf "  ${YELLOW}!${RESET} %s\n" "$*"; }
error() { printf "  ${RED}✘${RESET} %s\n" "$*"; }

sandbox_exists() {
    sbx ls 2>/dev/null | awk -v n="$SANDBOX_NAME" '$1 == n {found=1} END {exit !found}'
}

setting_is() { [ "$(sbx settings get "$1" 2>/dev/null)" = "$2" ]; }

# Appends to /etc/sandbox-persistent.sh, sourced before every bash in the sandbox.
append_to_persistent_sh_file() {
    sbx exec -i "$SANDBOX_NAME" bash -c 'cat >> /etc/sandbox-persistent.sh'
}

# Optional: silent when the host is already configured.
set_host_config() {
    setting_is clipboard.imagePaste true || {
        sbx settings set clipboard.imagePaste true >/dev/null && ok "clipboard.imagePaste"
    }
    setting_is kit.allowLocalKits true || {
        sbx settings set kit.allowLocalKits true >/dev/null && ok "kit.allowLocalKits"
    }
}

# Optional: silent when a github secret is already stored.
set_github_token() {
    sbx secret ls 2>/dev/null | awk '$3 == "github" {f=1} END {exit !f}' && return
    gh auth token | sbx secret set -g github >/dev/null && ok "github token stored"
}

create_sandbox() {
    # --kit only applies at create; `sbx kit add` restarts but preserves VM state.
    # sbx kit add "$SANDBOX_NAME" "$KIT_DIR"
    sbx create --name "$SANDBOX_NAME" claude . "$@" >/dev/null && ok "sandbox created"
}

set_git_identity() {
    GIT_USER_NAME=$(git config --global user.name)
    GIT_USER_EMAIL=$(git config --global user.email)
    GIT_COMMANDS="git config --global user.name \"$GIT_USER_NAME\""$'\n'
    GIT_COMMANDS+="git config --global user.email \"$GIT_USER_EMAIL\""
    printf '%s\n' "$GIT_COMMANDS" | append_to_persistent_sh_file
    ok "git identity  ${GREY}$GIT_USER_NAME <$GIT_USER_EMAIL>${RESET}"
}

# Make sure the default permission is --dangerously-skip-permissions
# as it overridden in "run_sandbox".
setup_claude_full_permissions() {
    printf '%s\n' 'claude() { command claude --dangerously-skip-permissions "$@"; }' \
        | append_to_persistent_sh_file
    ok "claude bypass mode"
}

# Powerline shell prompt so it's obvious the shell is inside a sandbox.
# \h is the sandbox name. Needs a Nerd/Powerline font for the  separator.
# swap __sbx_sep for a plain character if yours lacks it.
setup_shell_prompt() {
    append_to_persistent_sh_file <<'BLOCK'
if [ -n "${PS1-}" ]; then
    __sbx_sep=$''
    PS1='\[\e[38;5;231;48;5;27m\] SBX \[\e[38;5;27;48;5;240m\]'"$__sbx_sep"'\[\e[38;5;231;48;5;240m\] \h \[\e[38;5;240;48;5;236m\]'"$__sbx_sep"'\[\e[38;5;252;48;5;236m\] \w \[\e[0m\e[38;5;236m\]'"$__sbx_sep"'\[\e[0m\] '
fi
BLOCK
    ok "shell prompt"
}

run_sandbox() {
    run "shell"
    exec sbx exec -it "$SANDBOX_NAME" bash
}

validate() {
    step "Ready"
    # No --global on the git reads: that scope skips the [include] holding the identity.
    sbx exec "$SANDBOX_NAME" -- bash -lc '
printf "    git identity : %s\n" `git config list | grep name`
printf "    statusline   : %s\n" "$(jq -r ".statusLine.command // \"NOT SET\"" ~/.claude/settings.json 2>/dev/null)"
printf "    agent mode   : %s\n" "$(jq -r ".defaultMode // \"default\"" ~/.claude/settings.json 2>/dev/null)"
printf "    github https : %s\n" "$(gh auth status 2>&1 | grep -qi "logged in\|Active account" && echo "authenticated via proxy" || echo "unauthenticated (public repos only)")"
' 2>/dev/null || warn "could not verify sandbox state"
}

main() {
    if sandbox_exists; then
        title "$SANDBOX_NAME" "(existing)"
    else
        title "$SANDBOX_NAME" "(new)"
        set_host_config
        set_github_token
        create_sandbox "$@"
        set_git_identity
        setup_claude_full_permissions
        setup_shell_prompt
    fi
    # validate
    run_sandbox
}

main "$@"
